### ISSUE TITLE
Content: Labs Practice - Remote Pairing Assessment

### ISSUE THREAD

**Issue by prettyClouds** [joemoore/labs-practices-site#2]
### Summary

When interviewing developers, Labs had a remote pairing assessment.  There were guidelines on how to conduct the interview, prompt the candidate, and a scoring rubric.  

### Maturity of this Practice or Workshop

- [x] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

### Resources

I don't have access to **the video**, but I know there was one of Rob Mee floating around the Google Drive

**Comment by joemoore** [comment]
Sorry I did not get this notification!

This is an interesting proposal. I'm very familiar with the RPI/RPA, but unlike all of the other content on the site I feel the interview is a (well known?) trade secret, and I would not be comfortable publishing a guide to conducting the interview, given that in so doing it would also document how to inauthentically pass it. 

The magic of the RPI is the relationship built between interviewer and interviewee, and publishing the guide would make building an authentic version of that relationship impossible.

**Comment by joemoore** [comment]
Based on above comment, closing.
